"""add_gemini_model_to_user

Revision ID: 4c554c5d93b9
Revises: fe9b4d5c6095
Create Date: 2026-05-06 01:28:47.229993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c554c5d93b9'
down_revision = 'fe9b4d5c6095'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gemini_model')
    # ### end Alembic commands ###
