"""add_grading_id_to_answer

Revision ID: f09a724fca2a
Revises: e10d3714e2a9
Create Date: 2026-04-08 12:25:52.110484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09a724fca2a'
down_revision = 'e10d3714e2a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('grading_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_answers_grading_id'), 'answers', ['grading_id'], unique=False)
    op.create_foreign_key(None, 'answers', 'grading_sessions', ['grading_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_index(op.f('ix_answers_grading_id'), table_name='answers')
    op.drop_column('answers', 'grading_id')
    # ### end Alembic commands ###
